---
env:
  browser: true
  es6: true
  node: true
  jest: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: tsconfig.json
  ecmaVersion: 11
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
extends:
  - plugin:prettier/recommended
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
rules:
  prettier/prettier:
    - error
    - endOfLine: lf