---
env:
  browser: true
  es6: true
  node: true
  jest: true
plugins:
  - prettier
extends:
  - plugin:prettier/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  prettier/prettier:
    - error
    - endOfLine: lf
